import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'app_title': 'Sanad',
      'internet_exception':
          "We're unable to show results.\nPlease check your data\nconnection",
      'general_exception':
          "We're unable to unable to process your request.\nPlease try again",
      'retry': 'Retry',
      'error_while_communicating_with_server':
          'Error while communicating with server',
      'no_internet': 'No Internet',
      'request_time_out': 'Request Time Out',
      'internal_server_error': 'Internal server error',
      'invalid_url': 'Invalid Url',
      'error_while_communication': 'Error while communication',
      'sign_in_to_sanad': 'Sign in to Sanad',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password',
      'forgot_password_with_question': 'Forgot Password?',
      'sign_in': 'Sign in',
      'don’t_have_an_account': 'Don’t have an account?',
      'request_one': 'Request One?',
      'email_not_valid': 'Email not valid',
      'password_format_invalid': 'Password format invalid',
      'are_you_company_or_recruiter': 'Are you company or recruiter? ',
      'company': 'Company',
      'recruiter': 'Recruiter',
      'join_as_an_individual': 'Join as an individual',
      'password_at_least': 'Password (6+ characters)',
      'by_clicking_agree_join_or_continue_you_agree_to_the_linkedIn':
          'By clicking Agree & Join or Continue, you agree to the\nLinkedIn ',
      'user_agreement': 'User Agreement',
      'privacy_policy': 'Privacy Policy',
      'and': ', and , ',
      'cookie_policy': 'Cookie Policy.',
      'agree_and_join': 'Agree & Join',
      'already_have_an_account': 'Already have an account?',
      'looking_to_create_an_account_for_an_agency':
          'Looking to create an account for an agency?',
      'signup_as_agency': 'Signup as Agency',
      'please_fill_the_required_information':
          'Please fill the required information',
      'full_name': 'Full Name',
      'full_name_hint': 'Add your agency name',
      'full_name_error': 'Full name cannot be blank',
      'tagline': 'Tagline',
      'tagline_hint': 'ex: An information services from your business',
      'tagline_error': 'Tagline cannot be blank',
      'phone_number': 'Phone Number',
      'phone_number_hint': '+1(234) 567 8900',
      'phone_number_error': 'Phone number cannot be blank',
      'email_hint': 'Add your email address',
      'password_hint': '1234567',
      'email_error': 'Email cannot be blank',
      'upload_profile_picture': 'Upload Profile Picture',
      'choose_file': 'Choose file',
      'choose_file_hint': 'No file chosen',
      'add_note': 'Add note',
      'add_note_hint': 'write note',
      'continue': 'Continue',
      'home': 'Home',
      'search_home_hint': 'Search keyword or label',
      'search_hint': 'Search',
      'jobs_for_you': 'Jobs for you',
      'jobs_based_on_your_activity': 'Jobs based on your activity',
      'find_jobs': 'Find Jobs',
      'my_jobs': 'My Jobs',
      'wallet': 'Wallet',
      'account': 'Account',
      'payment': 'Payment',
      'next': 'Next',
      'no_worries_enter_your_email_for_reset_password':
          'No worries! Enter your email address, and we’ll send you a link to reset your password.',
      'otp_verification': 'OPT Verification',
      'enter_your_security_code_we_sent_to':
          'Enter your security code we sent to ',
      'resend_code': 'Resend code',
      'otp_code': 'OTP Code',
      'back_to_login': 'Back to Login',
      'password_reset_successfully': 'Password Reset Successfully',
      'password_reset_description':
          'Your Account password is reset successfully. Please login into your account.',
      'reset_password': 'Reset Password',
      'reset_password_description':
          'Your new password must be unique from those previously used.',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'verify': 'Verify',
      'email_verification': 'Email Verification',
      'location': 'Location',
      'private_job': 'Private Job',
      'public_job': 'Public Job',
      'applied': 'Applied',
      'saved': 'Saved',
      'invitation': 'Invitation',
      'profile': 'Profile',
      'notifications': 'Notifications',
      'analytics': 'Analytics',
      'transactions': 'Transactions',
      'payments': 'Payments',
      'payments_method': 'Payments Method',
      'rate_us': 'Rate Us',
      'settings': 'Settings',
      'about': 'About',
      'help': 'Help',
      'sign_out': 'Sign Out',
      'submit': 'Submit',
      'dismiss': 'Dismiss',
      'ob_1_title': 'Find Your Dream Job Today',
      'ob_1_description':
          'Get vacancies from 14000,00 resources in one\napp  Lorem ipsum dolor sit amet c,onsectetur\nadipiscing elit,',
      'ob_2_title': 'Your Path, Your Way',
      'ob_2_description':
          'Endless Opportunities, Just One Click Away,\namet c,onsectetur adipiscing elit, sed do\neiusmod tempor incididunt ut',
      'ob_3_title': 'Easy to Apply',
      'ob_3_description':
          'Lorem ipsum dolor sit amet c,onsectetur\nadipiscing elit, sed do eiusmod tempor\nincididunt ut labore et dolore',
      'skip': 'Skip',
      'message_cannot_be_blank': 'Message cannot be blank',
      'message_hint': 'Write something here',
      'your_message': 'Your message',
      'write_your_feedback_and_remarks': 'Write your feedback and remarks',
      'rate_us_dot': 'Rate us.',
      'rate_us_and_write_your_feedback': 'Rate us and write your feedback.',
      'note_cannot_be_blank': 'Note cannot be blank',
      'deposit_now': 'Deposit Now',
      'total_balance': 'Total Balance',
      'riyal': ' Riyal',
      'deposits': ' Deposits',
      'refunds': ' Refunds',
      'recent_transactions': ' Recent Transactions',
      'empty_transactions': "You don't have any transaction",
      'about_description':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolor\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolm\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do equip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\n\nIf you need help or you have any questions, feel free to contact me by email.\n\nexample@email.com',
      'sign_out_dash': 'Sign-out',
      'confirm_sign_out': 'Are you sure you want to Sign-out of your account?',
      'transaction_history': 'Transaction History',
      'track_your_list_of_transaction_here':
          'Track your list of transaction here',
      'payment_id': 'Payment ID',
      'amount': 'Amount',
      'payment_method': 'Payment Method',
      'action': 'Action',
      'yes': 'Yes',
      'no': 'No',
      'help_title': 'This Help Is Here for  Lorem ipsum sit',
      'help_description':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea.',
      'payment_history': 'Payment History',
      'track_your_list_of_payment_here': 'Track your list of payments here',
      'payment_capital': 'PAYMENT',
      'status': 'Status',
      'payment_details': 'Payment Details',
      'track_your_payment_details_here': 'Track your payment details here',
      'payment_amount': 'Payment amount',
      'invoice': 'Invoice',
      'payment_date': 'Payment Date',
      'download_invoice': 'Download Invoice',
      'no_help_history': 'No Help History',
      'no_jobs': 'No Jobs',
      'no_notification': 'No Notification',
      'no_payments': 'No Payments',
      'no_transactions': 'No Transactions',
      'your_wallet': 'Your wallet',
      'view_job': 'View Job',
      'job_details': 'Job Details',
      'description': 'Description',
      'experience_required': 'Experience Required',
      'candidates_required': 'Candidates required',
      'general': 'General',
      'requirements': 'Requirements',
      'additional_requirements': 'Additional Requirements',
      'are_you_open_to_relocating':
          'Would you prefer to work remotely, or are you open to relocating?',
      'open_to_relocating': 'Open to Relocating',
      'software_programs_do_you_know':
          'Which of the following software programs do you know? (You can select multiple options.)',
      'how_many_years_of_experience':
          'How many years of experience do you have?',
      'should_have_an_experience':
          'Should have an experience of more or equal to 5 Years',
      'apply_now': 'Apply Now',
      'apply_job': 'Apply Job',
      'linkedin_account': 'LinkedIn Account',
      'optional': ' (Optional)',
      'linkedin_account_hint': 'Input text',
      'upload_resume': 'Upload Resume',
      'discard': 'Discard',
      'click_to_upload': 'Click to upload',
      'drag_and_drop': ' or drag and drop',
      'file_format': 'SVG, PNG, JPG or GIF (MAX. 800x400px)',
    },
    'ur_PK': {'splash_screen': 'سپلیش اسکرین'},
  };
}
