import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'app_title': 'Sanad',
      'internet_exception':
          "We're unable to show results.\nPlease check your data\nconnection",
      'general_exception':
          "We're unable to unable to process your request.\nPlease try again",
      'retry': 'Retry',
      'error_while_communicating_with_server':
          'Error while communicating with server',
      'no_internet': 'No Internet',
      'request_time_out': 'Request Time Out',
      'internal_server_error': 'Internal server error',
      'invalid_url': 'Invalid Url',
      'error_while_communication': 'Error while communication',
      'sign_in_to_sanad': 'Sign in to Sanad',
      'email': 'Email',
      'please_select_country_code_first': 'Please select country code first',
      'invalid_phone_number_format': 'Invalid phone number format',
      'invalid_phone_number': 'Invalid phone number',
      'password': 'Password',
      'forgot_password': 'Forgot Password',
      'forgot_password_with_question': 'Forgot Password?',
      'sign_in': 'Sign in',
      'don’t_have_an_account': 'Don’t have an account?',
      'request_one': 'Request One?',
      'email_not_valid': 'Email not valid',
      'password_format_invalid': 'Password format invalid',
      'are_you_client_or_recruiter': 'Are you Client or Recruiter? ',
      'are_you_company_or_recruiter': 'Are you company or recruiter? ',
      'company': 'Company',
      'client': 'Client',
      'recruiter': 'Recruiter',
      'join_as_an_individual': 'Join as an individual',
      'join_as_an_agency': 'Join as an agency',
      'password_at_least': 'Password (6+ characters)',
      'by_clicking_agree_join_or_continue_you_agree_to_the_linkedIn':
          'By clicking Agree & Join or Continue, you agree to the\nLinkedIn ',
      'user_agreement': 'User Agreement',
      'privacy_policy': 'Privacy Policy',
      'and': ', and \n',
      'cookie_policy': 'Cookie Policy.',
      'agree_and_join': 'Agree & Join',
      'already_have_an_account': 'Already have an account?',
      'looking_to_create_an_account_for_an_agency':
          'Looking to create an account for an agency?',
      'signup_as_agency': 'Signup as Agency',
      'looking_to_create_an_account_for_an_individual':
          'Looking to create an account for an individual?',
      'signup_as_individual': 'Signup as Individual',
      'please_fill_the_required_information':
          'Please fill the required information',
      'full_name': 'Full Name',
      'full_name_hint': 'Enter your full name',
      'full_name_error': 'Full name cannot be blank',
      'agency_name': 'Agency Name',
      'agency_name_hint': 'Enter your agency name',
      'agency_name_error': 'Agency name cannot be blank',
      'tagline': 'Tagline',
      'tagline_hint': 'ex: An information services from your business',
      'tagline_error': 'Tagline cannot be blank',
      'phone_number': 'Phone Number',
      'phone_number_hint': '+1(234) 567 8900',
      'phone_number_error': 'Phone number cannot be blank',
      'email_hint': 'Add your email address',
      'password_hint': '1234567',
      'email_error': 'Email cannot be blank',
      'upload_profile_picture': 'Upload Profile Picture',
      'choose_file': 'Choose file',
      'choose_file_hint': 'No file chosen',
      'add_note': 'Add note',
      'add_note_hint': 'write note',
      'continue': 'Continue',
      'home': 'Home',
      'search_home_hint': 'Search keyword or label',
      'search_hint': 'Search',
      'jobs_for_you': 'Jobs for you',
      'jobs_based_on_your_activity': 'Jobs based on your activity',
      'find_jobs': 'Find Jobs',
      'my_jobs': 'My Jobs',
      'wallet': 'Wallet',
      'account': 'Account',
      'payment': 'Payment',
      'next': 'Next',
      'no_worries_enter_your_email_for_reset_password':
          'No worries! Enter your email address, and we’ll send you a link to reset your password.',
      'otp_verification': 'OPT Verification',
      'enter_your_security_code_we_sent_to':
          'Enter your security code we sent to ',
      'resend_code': 'Resend code',
      'otp_code': 'OTP Code',
      'back_to_login': 'Back to Login',
      'password_reset_successfully': 'Password Reset Successfully',
      'password_reset_description':
          'Your Account password is reset successfully. Please login into your account.',
      'reset_password': 'Reset Password',
      'reset_password_description':
          'Your new password must be unique from those previously used.',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'verify': 'Verify',
      'email_verification': 'Email Verification',
      'location': 'Location',
      'private_job': 'Private Job',
      'public_job': 'Public Job',
      'applied': 'Applied',
      'saved': 'Saved',
      'invitation': 'Invitation',
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'notifications': 'Notifications',
      'analytics': 'Analytics',
      'transactions': 'Transactions',
      'payments': 'Payments',
      'payments_method': 'Payments Method',
      'rate_us': 'Rate Us',
      'settings': 'Settings',
      'about': 'About ',
      'help': 'Help',
      'sign_out': 'Sign Out',
      'submit': 'Submit',
      'dismiss': 'Dismiss',
      'ob_1_title': 'Find Your Dream Job Today',
      'ob_1_description':
          'Get vacancies from 14000,00 resources in one\napp  Lorem ipsum dolor sit amet c,onsectetur\nadipiscing elit,',
      'ob_2_title': 'Your Path, Your Way',
      'ob_2_description':
          'Endless Opportunities, Just One Click Away,\namet c,onsectetur adipiscing elit, sed do\neiusmod tempor incididunt ut',
      'ob_3_title': 'Easy to Apply',
      'ob_3_description':
          'Lorem ipsum dolor sit amet c,onsectetur\nadipiscing elit, sed do eiusmod tempor\nincididunt ut labore et dolore',
      'skip': 'Skip',
      'message_cannot_be_blank': 'Message cannot be blank',
      'message_hint': 'Write something here',
      'your_message': 'Your message',
      'write_your_feedback_and_remarks': 'Write your feedback and remarks',
      'rate_us_dot': 'Rate us.',
      'rate_us_and_write_your_feedback': 'Rate us and write your feedback.',
      'note_cannot_be_blank': 'Note cannot be blank',
      'deposit_now': 'Deposit Now',
      'total_balance': 'Total Balance',
      'riyal': ' Riyal',
      'deposits': ' Deposits',
      'refunds': ' Refunds',
      'recent_transactions': ' Recent Transactions',
      'empty_transactions': "You don't have any transaction",
      'about_description':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolor\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolm\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do equip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\n\nIf you need help or you have any questions, feel free to contact me by email.\n\nexample@email.com',
      'sign_out_dash': 'Sign-out',
      'confirm_sign_out': 'Are you sure you want to Sign-out of your account?',
      'transaction_history': 'Transaction History',
      'track_your_list_of_transaction_here':
          'Track your list of transaction here',
      'payment_id': 'Payment ID',
      'amount': 'Amount',
      'payment_method': 'Payment Method',
      'action': 'Action',
      'yes': 'Yes',
      'no': 'No',
      'help_title': 'This Help Is Here for  Lorem ipsum sit',
      'help_description':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea.',
      'payment_history': 'Payment History',
      'track_your_list_of_payment_here': 'Track your list of payments here',
      'payment_capital': 'PAYMENT',
      'status': 'Status',
      'job_title': 'Job Title',
      'cv_name': 'CV Name',
      'view': 'View',
      'payment_details': 'Payment Details',
      'track_your_payment_details_here': 'Track your payment details here',
      'payment_amount': 'Payment amount',
      'invoice': 'Invoice',
      'payment_date': 'Payment Date',
      'download_invoice': 'Download Invoice',
      'no_help_history': 'No Help History',
      'no_jobs': 'No Jobs',
      'no_notification': 'No Notification',
      'no_payments': 'No Payments',
      'no_transactions': 'No Transactions',
      'revenue': 'Revenue',
      'your_wallet': 'Your wallet',
      'view_job': 'View Job',
      'job_details': 'Job Details',
      'experience_required': 'Experience Required',
      'candidates_required': 'Candidates required',
      'general': 'General',
      'requirements': 'Requirements',
      'additional_requirements': 'Additional Requirements',
      'are_you_open_to_relocating':
          'Would you prefer to work remotely, or are you open to relocating?',
      'open_to_relocating': 'Open to Relocating',
      'software_programs_do_you_know':
          'Which of the following software programs do you know? (You can select multiple options.)',
      'how_many_years_of_experience':
          'How many years of experience do you have?',
      'should_have_an_experience':
          'Should have an experience of more or equal to 5 Years',
      'apply_now': 'Apply Now',
      'apply_job': 'Apply Job',
      'linkedin_account': 'LinkedIn Account',
      'optional': ' (Optional)',
      'linkedin_account_hint': 'Input text',
      'upload_resume': 'Upload Resume',
      'discard': 'Discard',
      'click_to_upload': 'Click to upload',
      'drag_and_drop': ' or drag and drop',
      'file_format': 'SVG, PNG, JPG or GIF (MAX. 800x400px)',
      'back': 'Back',
      'experience_year_hint': 'Your Answer',
      'year': 'Year',
      'apply_again': 'Apply Again',
      'back_to_jobs': 'Back to Jobs',
      'application_sent_successfully': 'Application sent successfully',
      'application_submitted_successfully':
          'Your application has been sent & submitted\nsuccessfully.',
      'edit': 'Edit',
      'resume_name': 'Candidate Resume.pdf',
      'can_relocate': 'Can relocate',
      'can_you_relocate': 'XYZ Location: Can you relocate for this position?',
      'portfolio': 'Portfolio',
      'have_a_portfolio': 'Does your resume have a portfolio?',
      'certification': 'Certification',
      'have_mentioned_certification': 'Do you have mentioned certification?',
      'resume': 'Resume',
      'review': 'Review',
      'cvs_sublimed': 'CVs sublimed',
      'cvs_bought': 'CVs bought',
      'all_jobs': 'All Jobs',
      'active_jobs': 'Active Jobs',
      'application_response': 'Application Response',
      'accepted': 'Accepted',
      'total_cv_submitted': 'Total cv submitted',
      'total_cv_accepted': 'Total cv accepted',
      'recruiter_comment':
          '“Exceptional recruiter – professional, reliable, and results-driven.”',
      'mobile_number': 'Mobile Number',
      'hint_country_code': '+26',
      'hint_mobile_number': 'Enter number',
      'send_code': 'Send Code',
      'my_information': 'My Information',
      'my_picture': 'My Picture',
      'add_photo': 'Add Photo',
      'select_image_source': 'Select image source',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'first_name': 'First Name',
      'first_name_hint': 'Enter first name',
      'first_name_error': 'First name cannot be empty',
      'last_name': 'Last Name',
      'last_name_hint': 'Enter last name',
      'last_name_error': 'Last name cannot be empty',
      'street': 'Street',
      'street_hint': 'Enter street address',
      'street_error': 'Street address cannot be empty',
      'city_or_state': 'City,State',
      'city_or_state_hint': 'Enter city or state',
      'city_or_state_error': 'City,State cannot be empty',
      'postal_code': 'Postal Code',
      'postal_code_hint': 'Enter postal code',
      'postal_code_error': 'Postal code cannot be empty',
      'country': 'Country',
      'country_hint': 'Enter country',
      'country_error': 'Country cannot be empty',
      'description': 'Description',
      'description_hint': 'Enter description',
      'description_error': 'Description cannot bee empty',
      'organization_type': 'Organization Type',
      'company_size_employees': 'Company Size, Employees',
      'self_employed': 'Self-employed, Sole trader',
      'two_to_ten': '2-10',
      'eleven_to_fifty': '11-50',
      'fifty_one_to_two_hundred': '51-200',
      'two_hundred_one_to_five_hundred': '201-500',
      'organization_type_hint': 'Select Type',
      'organization_type_error': 'Please select organization type',
      'login': 'Login',
      'view_job_details': 'View Job Details',
      'submitted_cv': "Submitted CV's",
      'bought': 'Bought',
      'sign_up': 'Sign up',
      'dark_mode': 'Dark Mode',
      'sign_up_as_an_individual': 'Sign Up as an Individual',
      'sign_up_as_a_individual': 'Sign Up as a Individual',
      'sign_up_as_a_recruiter': 'Sign Up as a Recruiter',
      'sign_up_as_an_company': 'Sign Up as an Company',
      'sign_up_as_a_company': 'Sign Up as a Company',
      'sign_in_to_skill_bridge': 'Sign in to Skill Bridge',
      'upload_logo': 'Upload Logo',
      'website': 'Website',
      'website_hint': 'Add your company website',
      'website_error': 'Website cannot be empty',
      'remember_for_30_days': 'Remember for 30 days',
      'interested_industry': 'Interested industry',
      'interested_industry_hint': 'Select industry',
      'interested_industry_error': 'Please select industry',
      'view_all': 'View All',
      'transaction_details': 'Transaction Details',
      'account_number': 'Account Number',
      'transaction_date': 'Transaction Date',
      'transaction_time': 'Transaction Time',
      'transaction_type': 'Transaction Type',
      'id': 'ID',
      'method': 'Method',
      'privacy_policy_description':
          'Welcome to [Your App Name] (“we,” “our,” or “us”). Your privacy is important to us. This Privacy Policy explains how we collect, use, and protect your personal information when you use our app.\n\n1. Information We Collect\nPersonal Information: When you register or use our app, we may collect personal details such as your name, email address, phone number, and other contact information. Usage Data: We automatically collect information about how you interact with our app, including your device information, IP address, browser type, pages visited, and time spent on our app. Cookies and Tracking Technologies: We may use cookies and similar technologies to enhance your experience and analyze app usage\n\n2. How We Use Your Information\nWe use the information we collect to:Provide, operate, and maintain the appImprove, personalize, and expand our app featuresCommunicate with you, including sending updates, security alerts, and support messagesMonitor usage and analyze trends to improve the appComply with legal obligation\n\n3. Sharing Your Information\nWe do not sell, trade, or rent your personal information to third parties. We may share your information with:Service providers who help us operate the app (e.g., hosting, analytics) Law enforcement or government authorities if required by last\n\n4. Data Security\nWe take reasonable measures to protect your information from unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the internet is completely secure.\n\n5. Your Choices\nYou can update or correct your personal information in your account settings.\nYou may opt out of receiving promotional emails by following the unsubscribe instructions\nYou can disable cookies in your browser settings, though this may affect app functionality.',
      'terms_and_conditions': 'Terms & Conditions',
      'terms_and_conditions_description':
          'Last updated: 6/10/2025\nWelcome to Recruitment (“we,” “our,” or “us”). By downloading, accessing, or using our mobile application (“App”), you agree to be bound by the following terms and conditions (“Terms”). Please read them carefully.\n\n1. Acceptance of Terms\n By using our App, you agree to comply with and be legally bound by these Terms. If you do not agree, please do not use the App.\n\n2. Eligibility\nYou must be at least [age, usually 13 or 16 depending on jurisdiction] years old to use the App. By using the App, you represent and warrant that you meet this requirement.\n\n3. Use of the App\nYou agree to use the App only for lawful purposes and in a way that does not infringe the rights of, restrict, or inhibit anyone else’s use and enjoyment of the App. Prohibited behavior includes harassing or causing distress or inconvenience to any other user, transmitting obscene or offensive content, or disrupting the normal flow of dialogue within the App.\n\n4. User Accounts\nSome features of the App may require you to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use.\n\n5. Intellectual Property\nAll content, trademarks, logos, and intellectual property within the App are owned by or licensed to us. You may not copy, modify, distribute, sell, or lease any part of our App or included software.',
      'cookies_policy': 'Cookies Policy',
      'cookies_policy_description':
          'Last updated: 6/10/2025\nThis Cookies Policy explains how Recruitment (“we,” “our,” or “us”) uses cookies and similar technologies when you use our mobile application (“App”). By continuing to use our App, you consent to our use of cookies as described in this policy.\n\n1. What Are Cookies?\nCookies are small text files stored on your device (phone, tablet, or computer) when you visit or use an app or website. They help us recognize your device, enhance your user experience, and collect information about your usage.\n\n2. How We Use Cookies\nWe use cookies to:\nOperate and secure the App\nRemember your preferences and login details\nAnalyze App usage to improve performance and functionality\nProvide personalized content and experiences\n\n3. Types of Cookies We Use\nEssential Cookies: Necessary for basic App operations such as navigation and access to secure areas.\nPerformance Cookies: Help us understand how users interact with the App to improve its performance.\nFunctionality Cookies: Allow us to remember choices you make, like language preferences.\nThird-Party Cookies: Some features may use third-party services (like analytics or ads) that place their own cookies on your device.\n\n4. Managing Cookies\nMost mobile devices and browsers automatically accept cookies, but you can usually modify your settings to decline or delete them. Please note that disabling cookies may affect the functionality and performance of the App.\n\n5. Changes to This Policy\nWe may update this Cookies Policy from time to time. ',
      'employment_type': 'Employment Type',
      'salary_range': 'Salary Range',
      'seniority_level': 'Seniority Level',
      'job_post_type': 'Job Post Type',
      'price_per_cv': 'Price per CV',
      'company_size': 'Company Size',
      'company_type': 'Company Type',
      'you_have_paid': 'You’ve Paid',
      'view_cv': 'View Cv',
      'withdraw_funds': 'Withdraw Funds',
      'withdraw_now': 'Withdraw Now',
      'card': 'Card',
      'mada': 'Mada',
      'withdraw': 'Withdraw',
      'set_amount': 'Set Amount',
      'verification': 'Verification',
      'enter_the_4_digit_code_to_process_your_withdraw':
          'Enter the 4-digit code to process your withdraw',
      'i_didn_t_receive_the_code': 'I didn’t receive the code',
      'verify_withdraw': 'Verify Withdraw',
      'great_with_exclamation': 'Great!',
      'withdraw_success': 'Withdraw Success',
      'below_is_your_withdraw_summary': 'Below is your withdraw summary',
      'withdraw_destination': 'Withdraw Destination',
      'total_withdraw': 'Total withdraw',
      'add_new_payment_method': 'Add New Payment Method',
      'payment_methods': 'Payment Methods',
      'payment_methods_detail':
          'Any updates made to your payment method information will be applied to your upcoming scheduled payments',
      'save_details': 'Save Details',
      'file_selected': 'File Selected: ',
      'file_size': 'File Size: ',
      'experience': 'Experience',
      'does_your_resume_have_a_portfolio': 'Does your resume have a portfolio?',
      'do_you_have_mentioned_certification':
          'Do you have mentioned certification?',
    },
    'ur_PK': {'splash_screen': 'سپلیش اسکرین'},
  };
}
